# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.
default: &default
  demo_api_token: <%= ENV['DEMO_API_TOKEN'] %>

development:
  <<: *default
  secret_key_base: d1a865731a58ea39bb4b788ba5b6aeb6a9231aed80aa59580f7e3f4ccd12c11428b22e8b3fd497a92a89ca2aabc0e9d939dee6ed26aa914de519135c780d8cb8

test:
  <<: *default
  secret_key_base: 84d071936e323c7402dbc7cfd1f5b0a60af2ced87e78609f49139819b3e552bc9bf69ac192ddfbad2cfae711244c05a995682626e8ee8e8332627ed21bbc74c8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  <<: *default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
