#!/usr/bin/env bash
export AWS_ACCESS_KEY_ID=
export AWS_REGION=
export AWS_SECRET_ACCESS_KEY=
export DEMO_API_KEY=
export EXTERNAL_HOST=
export TWILIO_API_SID=
export TWILIO_API_TOKEN=
export TWILIO_PHONE_NUMBER=
